DROP TABLE IF EXISTS P03_produire;
DROP TABLE IF EXISTS P03_album;
DROP TABLE IF EXISTS P03_auteur;

--Création des tables
CREATE TABLE P03_album(
	bd_num INT PRIMARY KEY,
	bd_titre VARCHAR(100) NOT NULL, 
	bd_annee INT NOT NULL,
	bd_nbPages INT, 
	bd_prix FLOAT);
	
CREATE TABLE P03_auteur(
	aut_id SERIAL PRIMARY KEY,
	aut_nom VARCHAR(50) NOT NULL,
	aut_prenom VARCHAR(50) NOT NULL);
	
CREATE TABLE P03_produire(
	aut_id INT,
	bd_num INT,
	aut_role VARCHAR(50) NOT NULL CHECK(aut_role IN ('dessinateur', 'scénariste', 'coloriste')),
	PRIMARY KEY (aut_id, bd_num, aut_role), 
	FOREIGN KEY (aut_id) REFERENCES P03_auteur(aut_id),
	FOREIGN KEY (bd_num) REFERENCES P03_album(bd_num) );

	
--Alimentation de la table des albums
INSERT INTO P03_album VALUES
(1, '4 aventures de Spirou ...et Fantasio', 1950, 57,11.90),
(2, 'Il y a un sorcier à Champignac', 1951, 57,9.09),
(3, 'Les chapeaux noirs' , 1952, 57, 11.90 ),
(4, 'Spirou et les héritiers', 1952, 59, 11.90),
(5, 'Les voleurs du Marsupilami' , 1954, 58, 11.90),
(6, 'La corne de rhinocéros', 1955, 60, 11.90),
(7, 'Le dictateur et le champignon', 1956, 60, 11.90),
(8, 'La mauvaise tête', 1956, 55, 11.90),
(9, 'Le repaire de la murène', 1957, 60, 11.90),
(10,'Les pirates du silence', 1958, 60, 11.90),
(11, 'Le gorille a bonne mine', 1959, 59, 11.90),
(12,'Le nid des Marsupilamis',1960, 61, 11.90),
(13,'Le voyageur du mésozoïque',1960,61,11.90),
(14,'Le prisonnier du Bouddha',1960,61,11.90),
(15,'Z comme Zorglub',1961,61,11.90),
(16, 'L''ombre du Z', 1962, 61, 11.90),
(17,'Spirou et les hommes-bulles', 1964 ,61, 11.90),
(18,'QRN sur Bretzelburg',1966 ,61 ,11.90),
(19,'Panade à Champignac' ,1969,60,11.90),
(20,'Le faiseur d''or',1970,60,11.90),
(21,'Du glucose pour Noémie',1971,60,11.90),
(22,'L''abbaye truquée',1972,52,11.90),
(23,'Tora Torapa',1973,52,11.90),
(24,'Tembo Tabou',1974,44,11.90),
(25,'Le gri-gri du Niokolo-Koba',1974,44,11.90),
(26,'Du cidre pour les étoiles',1975,44,11.90),
(27,'L''Ankou',1977,44,11.90),
(28,'Kodo le tyran',1979,44,11.90),
(29,'Des haricots partout',1980,44,11.90),
(30,'La ceinture du grand froid',1983,44,11.90),
(31,'La boîte noire',1983,44,11.90),
(32,'Les faiseurs de silence',1944,44,11.90),
(33,'Virus',1984,44,11.90),
(34,'Aventure en Australie',1985,44,11.90),
(35,'Qui arrêtera Cyanure ?',1985,44,11.90),
(36,'L''horloger de la comète',1986,44,11.90),
(37,'Le réveil du Z',1986,44,11.90),
(38,'La jeunesse de Spirou',1987,46,11.90),
(39,'Spirou à New York',1987,44,11.90),
(40,'La frousse aux trousses',1988,44,11.90),
(41,'La vallée des bannis',1989,44,11.90),
(42,'Spirou et Fantasio à Moscou',1990,44,11.90),
(43,'Vito la déveine',1991,44,11.90),
(44,'Le rayon noir',1993,44,11.90),
(45,'Luna fatale',1995,44,11.90),
(46,'Machine qui rêve',1998,44,11.90),
(47,'Paris-sous-Seine',2004,46,11.90),
(48,'L''Homme qui ne voulait pas mourir',2005,54,11.90),
(49,'Spirou et Fantasio à Tokyo',2006,62,11.90),
(50,'Aux sources du Z',2008,48,11.90),
(51,'Alerte aux Zorkons',2010,54,11.90),
(52,'La face cachée du Z',2011,47,11.90),
(53,'Dans les griffes de la Vipère',2013,46,11.90),
(54,'Le Groom de Sniper Alley',2014,46,11.90),
(55,'La colère du Marsupilami',2016,54,11.90),
(56,'La mort de Spirou',2022,57,11.90),
(57,'3 Histoires Extraordinaires',2022,167,5.00),
(58,'Bravo les Brothers',2012,88,25.95),
(59,'La Foire aux gangsters',2012,48,25.95),
(60,'La Peur au bout du fil',2013,64,25.95),
(61,'Vacances sans histoires',2014,82,25.95),
(62,'La Quick Super',2014,68,25.95),
(63,'Spirou et les petits formats',2021,110,29.95),
(64,'L''héritage',1976,45,11.90),
(65,'Radar le robot',1976,41,11.90),
(66,'La Voix sans maître (et 5 autres aventures)',2003,45,11.90),
(67,'Fantasio et le fantôme (et 4 autres aventures)',2003,46,11.90),
(68,'Les Folles Aventures de Spirou',2017,46,39.33),
(79,'Spirou et l''Aventure',1948,127,55.99),
(70,'Spirou et Fantasio',1948,104,118.95);


--Alimentation de la table des auteurs
INSERT INTO P03_auteur (aut_nom,aut_prenom) VALUES
('Franquin','André'),
('Darc','Jean'),
('Gillain','Joseph'),
('Almo','Jo'),
('Rosy','Maurice'),
('Maltaite','Willy'),
('Regnier','Michel'),
('De Mesmaeker','Jean'),
('Roba','Jean'),
('Culliford','Pierre'),
('Goossens','Roland'),
('Fournier','Jean Claude'),
('Cauvin','Raoul'),
('Broca','Nicolas'),
('Vandevelde','Philippe'),
('Geurts','Jean-Richard'),
('De Becker','Stéphane'),
('Morvan','Jean-David'),
('Munuera','Jose Luis'),
('Lerolle','Christian'),
('Colombo','Pedro J.'),
('Le Saout','Anthony'),
('Le Pennetier','Yann'),
('Vehlmann','Fabien'),
('Chivard','Yoann'),
('Boulard','Hubert'),
('Croix','Laucrence'),
('Guerrive','Sophie'),
('Abitan','Benjamin'),
('Doucet','Alex'),
('Jannin','Frédéric'),
('Velter','Robert'),
('Chaland','Yves'),
('Schwartz','Olivier');


--Alimentation de la table de l'association	
INSERT INTO P03_produire VALUES
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'), (SELECT bd_num FROM P03_album WHERE bd_titre ='4 aventures de Spirou ...et Fantasio'),'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),(SELECT bd_num FROM P03_album WHERE bd_titre ='4 aventures de Spirou ...et Fantasio'),'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'), (SELECT bd_num FROM P03_album WHERE bd_titre ='Il y a un sorcier à Champignac'),'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),(SELECT bd_num FROM P03_album WHERE bd_titre ='Il y a un sorcier à Champignac'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Darc'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Il y a un sorcier à Champignac'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les chapeaux noirs'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Gillain'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les chapeaux noirs'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les chapeaux noirs'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Gillain'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les chapeaux noirs'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et les héritiers'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et les héritiers'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les voleurs du Marsupilami'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les voleurs du Marsupilami'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Almo'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les voleurs du Marsupilami'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La corne de rhinocéros'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La corne de rhinocéros'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le dictateur et le champignon'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le dictateur et le champignon'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Rosy'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le dictateur et le champignon'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La mauvaise tête'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La mauvaise tête'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le repaire de la murène'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le repaire de la murène'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les pirates du silence'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les pirates du silence'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Rosy'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les pirates du silence'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le gorille a bonne mine'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le gorille a bonne mine'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le nid des Marsupilamis'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le nid des Marsupilamis'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le voyageur du mésozoïque'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le voyageur du mésozoïque'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Regnier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le voyageur du mésozoïque'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le prisonnier du Bouddha'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le prisonnier du Bouddha'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Regnier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le prisonnier du Bouddha'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Z comme Zorglub'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Z comme Zorglub'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Regnier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Z comme Zorglub'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''ombre du Z'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''ombre du Z'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Regnier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''ombre du Z'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et les hommes-bulles'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et les hommes-bulles'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Roba'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et les hommes-bulles'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='QRN sur Bretzelburg'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='QRN sur Bretzelburg'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Regnier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='QRN sur Bretzelburg'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),(SELECT bd_num FROM P03_album WHERE bd_titre ='Panade à Champignac'),'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Panade à Champignac'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Culliford'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Panade à Champignac'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Goossens'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Panade à Champignac'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='De Mesmaeker'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Panade à Champignac'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le faiseur d''or'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le faiseur d''or'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le faiseur d''or'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Du glucose pour Noémie'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Du glucose pour Noémie'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Du glucose pour Noémie'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''abbaye truquée'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''abbaye truquée'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''abbaye truquée'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Tora Torapa'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Tora Torapa'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Tembo Tabou'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Tembo Tabou'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Regnier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Tembo Tabou'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Roba'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Tembo Tabou'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Maltaite'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Tembo Tabou'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le gri-gri du Niokolo-Koba'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le gri-gri du Niokolo-Koba'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Du cidre pour les étoiles'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Du cidre pour les étoiles'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''Ankou'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''Ankou'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Des haricots partout'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Des haricots partout'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Cauvin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La ceinture du grand froid'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Broca'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La ceinture du grand froid'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Cauvin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La boîte noire'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Broca'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La boîte noire'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Cauvin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les faiseurs de silence'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Broca'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les faiseurs de silence'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Virus'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Virus'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Aventure en Australie'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Aventure en Australie'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Qui arrêtera Cyanure ?'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Qui arrêtera Cyanure ?'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''horloger de la comète'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''horloger de la comète'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le réveil du Z'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le réveil du Z'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='De Becker'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le réveil du Z'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La jeunesse de Spirou'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La jeunesse de Spirou'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou à New York'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou à New York'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='De Becker'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou à New York'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La frousse aux trousses'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La frousse aux trousses'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='De Becker'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La frousse aux trousses'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Vacances sans histoires'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Vacances sans histoires'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Jannin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Vacances sans histoires'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Quick Super'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Quick Super'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Jannin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Quick Super'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et les petits formats'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Roba'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et les petits formats'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Roba'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et les petits formats'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et les petits formats'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Jannin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et les petits formats'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''héritage'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''héritage'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Radar le robot'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Radar le robot'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Gillain'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Radar le robot'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Voix sans maître (et 5 autres aventures)'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Velter'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Voix sans maître (et 5 autres aventures)'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Voix sans maître (et 5 autres aventures)'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Broca'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Voix sans maître (et 5 autres aventures)'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La vallée des bannis'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La vallée des bannis'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='De Becker'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La vallée des bannis'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et Fantasio à Moscou'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et Fantasio à Moscou'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='De Becker'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et Fantasio à Moscou'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Vito la déveine'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Vito la déveine'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='De Becker'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Vito la déveine'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le rayon noir'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le rayon noir'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='De Becker'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le rayon noir'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Luna fatale'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Luna fatale'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='De Becker'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Luna fatale'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Machine qui rêve'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Machine qui rêve'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='De Becker'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Machine qui rêve'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Morvan'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Paris-sous-Seine'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Munuera'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Paris-sous-Seine'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Lerolle'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Paris-sous-Seine'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Morvan'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''Homme qui ne voulait pas mourir'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Munuera'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''Homme qui ne voulait pas mourir'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Lerolle'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='L''Homme qui ne voulait pas mourir'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Morvan'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et Fantasio à Tokyo'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Munuera'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et Fantasio à Tokyo'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Colombo'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et Fantasio à Tokyo'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Lerolle'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et Fantasio à Tokyo'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Le Saout'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et Fantasio à Tokyo'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Morvan'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Aux sources du Z'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Le Pennetier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Aux sources du Z'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Munuera'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Aux sources du Z'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Lerolle'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Aux sources du Z'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vehlmann'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Alerte aux Zorkons'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Chivard'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Alerte aux Zorkons'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Boulard'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Alerte aux Zorkons'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vehlmann'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La face cachée du Z'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Chivard'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La face cachée du Z'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Boulard'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La face cachée du Z'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vehlmann'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Dans les griffes de la Vipère'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Chivard'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Dans les griffes de la Vipère'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Boulard'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Dans les griffes de la Vipère'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vehlmann'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le Groom de Sniper Alley'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Chivard'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le Groom de Sniper Alley'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Croix'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Le Groom de Sniper Alley'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vehlmann'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La colère du Marsupilami'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Chivard'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La colère du Marsupilami'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Croix'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La colère du Marsupilami'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Guerrive'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La mort de Spirou'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Abitan'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La mort de Spirou'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Schwartz'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La mort de Spirou'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Doucet'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La mort de Spirou'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vandevelde'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='3 Histoires Extraordinaires'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='3 Histoires Extraordinaires'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Geurts'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='3 Histoires Extraordinaires'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Bravo les Brothers'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Bravo les Brothers'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Jannin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Bravo les Brothers'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Foire aux gangsters'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Foire aux gangsters'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Jannin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Foire aux gangsters'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Regnier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Peur au bout du fil'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Peur au bout du fil'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Jannin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='La Peur au bout du fil'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Vehlmann'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les Folles Aventures de Spirou'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Chivard'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les Folles Aventures de Spirou'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Croix'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Les Folles Aventures de Spirou'),
  'coloriste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Gillain'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et l''Aventure'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Gillain'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et l''Aventure'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et Fantasio'),
  'scénariste'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Spirou et Fantasio'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Chaland'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Fantasio et le fantôme (et 4 autres aventures)'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Franquin'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Fantasio et le fantôme (et 4 autres aventures)'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Gillain'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Fantasio et le fantôme (et 4 autres aventures)'),
  'dessinateur'),
((SELECT aut_id FROM P03_auteur WHERE aut_nom ='Fournier'),
  (SELECT bd_num FROM P03_album WHERE bd_titre ='Fantasio et le fantôme (et 4 autres aventures)'),
  'dessinateur');
